// Decompiled with JetBrains decompiler
// Type: TLE_Analyser.SatVariables
// Assembly: TLE Analyser, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: CA947322-4F35-434B-8CA2-411C8482C9EF
// Assembly location: C:\Users\Olivier\OneDrive\OLIVIER\LOISIRS\TLEANALYSER\TLE Analyser.exe
// XML documentation location: C:\Users\Olivier\OneDrive\OLIVIER\LOISIRS\TLEANALYSER\TLE Analyser.xml

using System.Diagnostics;

namespace TLE_Analyser
{
  public class SatVariables
  {
    protected internal double argpo;
    protected internal double bstar;
    protected internal double ecco;
    protected internal double inclo;
    protected internal double mo;
    protected internal double no;
    protected internal double omegao;
    protected internal Dates epoque;
    protected internal bool init;
    protected internal bool isimp;
    protected internal int irez;
    protected internal double ao;
    protected internal double argpdot;
    protected internal double argpm;
    protected internal double argpp;
    protected internal double atime;
    protected internal double aycof;
    protected internal double cc1;
    protected internal double cc4;
    protected internal double cc5;
    protected internal double cnodm;
    protected internal double con41;
    protected internal double con42;
    protected internal double cosim;
    protected internal double cosio;
    protected internal double cosio2;
    protected internal double cosomm;
    protected internal double d2;
    protected internal double d2201;
    protected internal double d2211;
    protected internal double d3;
    protected internal double d3210;
    protected internal double d3222;
    protected internal double d4;
    protected internal double d4410;
    protected internal double d4422;
    protected internal double d5220;
    protected internal double d5232;
    protected internal double d5421;
    protected internal double d5433;
    protected internal double day;
    protected internal double dedt;
    protected internal double del1;
    protected internal double del2;
    protected internal double del3;
    protected internal double delmo;
    protected internal double delt;
    protected internal double didt;
    protected internal double dmdt;
    protected internal double domdt;
    protected internal double dndt;
    protected internal double dnodt;
    protected internal double eccsq;
    protected internal double ee2;
    protected internal double e3;
    protected internal double em;
    protected internal double emsq;
    protected internal double ep;
    protected internal double eta;
    protected internal double f220;
    protected internal double f221;
    protected internal double f311;
    protected internal double f321;
    protected internal double f322;
    protected internal double f330;
    protected internal double f441;
    protected internal double f442;
    protected internal double f522;
    protected internal double f523;
    protected internal double f542;
    protected internal double f543;
    protected internal double g200;
    protected internal double g201;
    protected internal double g211;
    protected internal double g300;
    protected internal double g310;
    protected internal double g322;
    protected internal double g410;
    protected internal double g422;
    protected internal double g520;
    protected internal double g521;
    protected internal double g532;
    protected internal double g533;
    protected internal double gam;
    protected internal double gsto;
    protected internal double inclm;
    protected internal double mdot;
    protected internal double mm;
    protected internal double mp;
    protected internal double nm;
    protected internal double nodecf;
    protected internal double nodedot;
    protected internal double nodem;
    protected internal double omegap;
    protected internal double omeosq;
    protected internal double omgcof;
    protected internal double posq;
    protected internal double rp;
    protected internal double rtemsq;
    protected internal double rteosq;
    protected internal double s1;
    protected internal double s2;
    protected internal double s3;
    protected internal double s4;
    protected internal double s5;
    protected internal double s6;
    protected internal double s7;
    protected internal double se2;
    protected internal double se3;
    protected internal double sgh2;
    protected internal double sgh3;
    protected internal double sgh4;
    protected internal double sh2;
    protected internal double sh3;
    protected internal double si2;
    protected internal double si3;
    protected internal double sinim;
    protected internal double sinio;
    protected internal double sinmao;
    protected internal double sinomm;
    protected internal double sl2;
    protected internal double sl3;
    protected internal double sl4;
    protected internal double snodm;
    protected internal double ss1;
    protected internal double ss2;
    protected internal double ss3;
    protected internal double ss4;
    protected internal double ss5;
    protected internal double ss6;
    protected internal double ss7;
    protected internal double sz1;
    protected internal double sz2;
    protected internal double sz3;
    protected internal double sz11;
    protected internal double sz12;
    protected internal double sz13;
    protected internal double sz21;
    protected internal double sz22;
    protected internal double sz23;
    protected internal double sz31;
    protected internal double sz32;
    protected internal double sz33;
    protected internal double t;
    protected internal double t2cof;
    protected internal double t3cof;
    protected internal double t4cof;
    protected internal double t5cof;
    protected internal double x1mth2;
    protected internal double x7thm1;
    protected internal double xfact;
    protected internal double xi2;
    protected internal double xi3;
    protected internal double xincp;
    protected internal double xgh2;
    protected internal double xgh3;
    protected internal double xgh4;
    protected internal double xh2;
    protected internal double xh3;
    protected internal double xl2;
    protected internal double xl3;
    protected internal double xl4;
    protected internal double xlamo;
    protected internal double xlcof;
    protected internal double xli;
    protected internal double xmcof;
    protected internal double xni;
    protected internal double xpidot;
    protected internal double z1;
    protected internal double z2;
    protected internal double z3;
    protected internal double z11;
    protected internal double z12;
    protected internal double z13;
    protected internal double z21;
    protected internal double z22;
    protected internal double z23;
    protected internal double z31;
    protected internal double z32;
    protected internal double z33;
    protected internal double zmol;
    protected internal double zmos;

    [DebuggerNonUserCode]
    public SatVariables()
    {
    }
  }
}
